renderer-type: MULTI_THREAD
thread-count: 8
affine-count: 9
symmetry-count: 5
samples: 10
iterations: 1000000
image-width: 800
image-height: 800
image-format: PNG
rect-x: -2
rect-y: -2
rect-width: 4
rect-height: 4
transformation-types:
    - DISK
#    - HEART
#    - HYPERBOLIC
#    - POLAR
#    - SINUSOIDAL
#    - SPHERE
#    - SWIRL
#    - WAVES
correction-type: GAMMA_CORRECTION
gamma: 1.5
